import * as React from "react"
import { useState, useEffect } from "react"
import { AIAttachment } from "../../types"
import { PredictionResult } from "../../contracts"
import { RiskPanel } from "../intelligence/RiskPanel"
import { SHAPBreakdown } from "../intelligence/SHAPBreakdown"
import { BiomarkerTimeline } from "../intelligence/BiomarkerTimeline"
import { ChevronDown, ChevronRight, Activity } from "lucide-react"
import { trackAttachmentExpand } from "../../telemetry"

interface AttachmentRendererProps {
  attachments?: AIAttachment[]
  messageId: string
}

function AttachmentWrapper({ attachment, messageId }: { attachment: AIAttachment, messageId: string }) {
  const [isExpanded, setIsExpanded] = useState(true)

  const toggleExpand = () => {
    const newState = !isExpanded
    setIsExpanded(newState)
    trackAttachmentExpand(attachment.type, newState ? "expand" : "collapse", messageId)
  }

  if (attachment.type === "prediction") {
    const data = attachment.data as PredictionResult
    return (
      <div className="flex flex-col w-full border border-neutral-800/50 rounded-xl overflow-hidden bg-[#0A0D14]/50">
        {/* Attachment Header */}
        <button 
          onClick={toggleExpand}
          className="flex items-center justify-between w-full p-3 hover:bg-white/5 transition-colors"
        >
          <div className="flex items-center gap-2">
            <Activity className="w-4 h-4 text-cyan-500" />
            <span className="text-xs font-semibold text-neutral-300 tracking-wide uppercase">
              Predictive Analysis
            </span>
            {data.risk && (
              <span className={`text-[10px] px-2 py-0.5 rounded-full bg-neutral-900 border border-neutral-800 ${
                data.risk.level === "HIGH" ? "text-rose-400" :
                data.risk.level === "MODERATE" ? "text-amber-400" : "text-emerald-400"
              }`}>
                {data.risk.level} RISK
              </span>
            )}
          </div>
          <div className="text-neutral-500">
            {isExpanded ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
          </div>
        </button>

        {/* Attachment Body */}
        {isExpanded && (
          <div className="p-4 pt-0 flex flex-col gap-4 border-t border-neutral-800/30">
            {(data.modelVersion || data.generatedBy) && (
              <div className="text-[10px] text-neutral-600 uppercase tracking-widest font-mono mt-3">
                Generated by {data.generatedBy || "AI"} • Model: {data.modelVersion || "unknown"}
              </div>
            )}
            <RiskPanel assessment={data.risk} confidenceScore={data.explainability.confidenceScore} />
            <BiomarkerTimeline biomarkers={data.biomarkers} />
            <SHAPBreakdown explainability={data.explainability} />
          </div>
        )}
      </div>
    )
  }

  return null
}

export function AttachmentRenderer({ attachments, messageId }: AttachmentRendererProps) {
  if (!attachments || attachments.length === 0) return null

  return (
    <div className="flex flex-col gap-3 mt-4 w-full max-w-full">
      {attachments.map((attachment, index) => (
        <AttachmentWrapper key={index} attachment={attachment} messageId={messageId} />
      ))}
    </div>
  )
}
